apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: dsjobset-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: wlcg.cern.ch/v1
    resource: dsjobsets
  childResources:
  - apiVersion: batch/v1
    resource: jobs
    updateStrategy:
      method: Recreate
  - apiVersion: v1
    resource: configmaps
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://dsjobset-controller.default/sync
