apiVersion: wlcg.cern.ch/v1
kind: DatasetJobSet
metadata:
  name: task
spec:
  taskid: 111120
  inDS: user.mguth:user.mguth.DL1_new_configs
  outDS: user.lheinric:outputtest.v12
  user: lheinric
  outputs:
  - out.json
  exec_template: echo %IN | tee out.json
  image: alpine
