apiVersion: wlcg.cern.ch/v1
kind: DatasetJobSet
metadata:
  name: task
spec:
  taskid: 111119
  inDS: user.lheinric:testhpscan.v2
  outDS: user.lheinric:outputtest.v11
  user: lheinric
  outputs:
  - out.json
  exec_template: echo %IN | tee out.json
  image: alpine
